### ISSUE TITLE
Error: failed to load 'sap/base/util/deepEqual.js'

### ISSUE THREAD

**Issue by danielang** [cevou/openui5-redux-model#1]
If I require `redux/ReduxModel` the following error was logged in the browser console:
```
Uncaught Error: failed to load 'sap/base/util/deepEqual.js' from /resources/sap/base/util/deepEqual.js: 404 - Not Found
    at makeNestedError (http://127.0.0.1:8081/resources/sap-ui-core.js:96:37)
    at requireModule (http://127.0.0.1:8081/resources/sap-ui-core.js:103:1990)
    at requireAll (http://127.0.0.1:8081/resources/sap-ui-core.js:105:551)
    at defineModule (http://127.0.0.1:8081/resources/sap-ui-core.js:108:178)
    at Object.ui5Define [as define] (http://127.0.0.1:8081/resources/sap-ui-core.js:107:1007)
    at eval (http://127.0.0.1:8081/libraries/openui5-redux-model/dist/redux/ReduxListBinding.js?eval:1:8)
    at eval (<anonymous>)
    at execModule (http://127.0.0.1:8081/resources/sap-ui-core.js:104:1406)
    at requireModule (http://127.0.0.1:8081/resources/sap-ui-core.js:103:2080)
    at requireAll (http://127.0.0.1:8081/resources/sap-ui-core.js:105:551)
Caused by: Error: 404 - Not Found
    at a (http://127.0.0.1:8081/resources/sap-ui-core.js:99:88)
    at XMLHttpRequest.<anonymous> (http://127.0.0.1:8081/resources/sap-ui-core.js:99:307)
    at XMLHttpRequest.send (<anonymous>:1:781)
    at loadSyncXHR (http://127.0.0.1:8081/resources/sap-ui-core.js:99:401)
    at requireModule (http://127.0.0.1:8081/resources/sap-ui-core.js:103:1910)
    at requireAll (http://127.0.0.1:8081/resources/sap-ui-core.js:105:551)
    at defineModule (http://127.0.0.1:8081/resources/sap-ui-core.js:108:178)
    at Object.ui5Define [as define] (http://127.0.0.1:8081/resources/sap-ui-core.js:107:1007)
    at eval (http://127.0.0.1:8081/libraries/openui5-redux-model/dist/redux/ReduxListBinding.js?eval:1:8)
    at eval (<anonymous>)
```

I searched for the file `deepEqual.js` in all recent versions of UI5, but I can not find it. In the directory `sap/base/util/` is only a file named `equal.js`

**Comment by cevou** [comment]
Which version of UI5 are you using? It is part of the latest 1.58:
https://github.com/SAP/openui5/blob/rel-1.58/src/sap.ui.core/src/sap/base/util/deepEqual.js

**Comment by danielang** [comment]
I am using the current version of OpenUI5 (Version 1.56.10)

Is their the posibility to use the following method [https://[open/sap]ui5.hana.ondemand.com/resources/sap/base/util/equal.js](https://openui5.hana.ondemand.com/resources/sap/base/util/equal.js)? It seems that this is the exact same method. Just the filename has been changed and a log statement has been added.

**Comment by cevou** [comment]
You can use the 0.3.x version, which should be compatible with 1.56
